const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={stars:new Set(),visited:new Set(),found:new Set(),rating:5,quizIndex:0,quizScore:0,answered:false,shots:0};
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
function earnStar(key,message){if(state.stars.has(key))return;state.stars.add(key);$("#starCount").textContent=state.stars.size;toast(`★ ${message} (${state.stars.size}/6)`)}

const eraData={
 gojoseon:{year:"고조선",title:"단군 이야기와 최초의 국가",text:"『삼국유사』에는 단군왕검이 고조선을 세웠다는 건국 이야기가 전합니다. 고조선은 청동기 문화를 바탕으로 성장했고, 기원전 2세기 무렵에는 한반도 북부와 요동 일대의 강력한 정치 세력이었습니다. 8조법을 통해 생명과 노동력, 사유 재산을 중요하게 여긴 사회였음을 짐작할 수 있습니다.",event:"건국 이야기 · 위만조선 · 한 군현 설치",life:"비파형 동검, 고인돌, 농경과 계급 사회",heritage:"고인돌 · 비파형 동검 · 단군 신화",question:"건국 이야기는 한 공동체의 생각과 바람을 어떻게 보여 줄까요?"},
 three:{year:"기원전 1세기~668",title:"고구려·백제·신라 그리고 가야",text:"여러 나라가 성장해 경쟁하고 교류했습니다. 고구려는 넓은 영토와 힘찬 고분 벽화를, 백제는 섬세하고 우아한 불교 문화를, 신라는 금관과 화랑 문화를 발전시켰습니다. 낙동강 유역의 가야는 철 생산과 해상 교역으로 성장했습니다. 신라는 당과 연합해 백제와 고구려를 무너뜨린 뒤 당의 세력을 몰아냈습니다.",event:"광개토대왕 · 백제 문화 전파 · 신라의 삼국 통합",life:"시장과 농경, 불교 수용, 철기와 국제 교류",heritage:"고구려 고분벽화 · 백제 금동대향로 · 신라 금관 · 가야 철갑",question:"네 나라가 서로 경쟁하면서도 문화를 주고받은 흔적은 무엇일까요?"},
 northsouth:{year:"698~926",title:"통일신라와 발해의 남북국 시대",text:"신라는 대동강 이남을 통합한 뒤 불교 예술과 국제 교류를 발전시켰습니다. 북쪽에서는 고구려 유민 대조영이 발해를 세워 고구려 문화를 계승했습니다. 발해는 ‘해동성국’이라 불릴 만큼 성장했고, 신라의 경주에는 서역인을 포함한 여러 지역의 사람들이 오갔습니다.",event:"신문왕의 제도 정비 · 대조영의 발해 건국",life:"경주의 국제 도시 문화, 발해의 온돌과 기와",heritage:"불국사 · 석굴암 · 성덕대왕신종 · 발해 정효공주묘",question:"통일신라만이 아니라 발해를 함께 배워야 하는 까닭은 무엇일까요?"},
 goryeo:{year:"918~1392",title:"고려, ‘Korea’의 이름이 되다",text:"왕건이 후삼국을 통일하고 세운 고려는 다양한 세력을 포용했습니다. 거란과 몽골의 침입을 겪으면서도 문화를 이어 갔으며, 벽란도를 통해 송·아라비아 상인과 교류했습니다. 불교문화, 청자, 금속활자와 팔만대장경은 고려인의 기술과 미감을 보여 줍니다.",event:"후삼국 통일 · 거란 침입 · 무신정변 · 몽골 항쟁",life:"벽란도 국제무역, 불교 행사, 향·부곡·소",heritage:"고려청자 · 팔만대장경 · 『직지』",question:"전쟁 중에 팔만대장경을 만든 사람들의 마음은 무엇이었을까요?"},
 joseon:{year:"1392~1897",title:"유교 국가와 새로운 문자",text:"조선은 성리학을 통치 원리로 삼고 중앙집권 체제를 정비했습니다. 세종 때 훈민정음, 측우기, 농사직설 등이 만들어졌습니다. 임진왜란과 병자호란을 겪은 뒤 사회·경제가 변했고, 후기에는 실학과 서민 문화가 성장했습니다. 신분에 따른 차별과 여성의 제약 같은 한계도 있었습니다.",event:"조선 건국 · 훈민정음 · 임진왜란 · 영·정조 개혁",life:"한양의 시전, 농업, 향촌 사회, 후기 장시 발달",heritage:"종묘 · 조선왕조실록 · 수원화성 · 판소리",question:"훈민정음은 지식과 정보의 주인을 어떻게 바꾸었을까요?"},
 empire:{year:"1876~1910",title:"개항, 개혁 그리고 대한제국",text:"개항 뒤 새로운 문물과 제도가 들어왔지만 외세의 경쟁도 심해졌습니다. 갑오개혁으로 신분제가 공식 폐지되고, 독립협회는 자주독립과 국민의 권리를 주장했습니다. 고종은 1897년 대한제국을 선포하고 근대화를 추진했으나 일본의 침략이 심해져 1910년 국권을 빼앗겼습니다.",event:"강화도조약 · 동학농민운동 · 독립협회 · 대한제국",life:"전차·전등·신문 등장, 근대 학교와 병원 설립",heritage:"환구단 · 독립문 · 덕수궁 석조전",question:"새로운 문물을 받아들이면서 자주성을 지키려면 무엇이 필요했을까요?"},
 occupation:{year:"1910~1945",title:"식민 지배에 맞선 독립운동",text:"일제는 토지와 자원을 수탈하고 한국인의 언어와 문화를 억압했습니다. 1919년 3·1운동 뒤 대한민국 임시정부가 수립됐고, 국내외에서 의병·외교·교육·문화·무장 투쟁 등 다양한 독립운동이 이어졌습니다. 학생과 노동자, 농민, 여성도 중요한 주체였습니다.",event:"3·1운동 · 임시정부 · 봉오동·청산리 전투 · 광복군",life:"민족학교, 한글 연구, 강제동원과 생활 통제",heritage:"독립선언서 · 임시정부 청사 · 독립운동 기록",question:"서로 다른 방법의 독립운동은 어떻게 같은 목표로 연결됐을까요?"},
 republic:{year:"1945~1987",title:"광복, 정부 수립과 한국전쟁",text:"1945년 8월 15일 일제의 식민 지배에서 벗어나 광복을 맞았습니다. 그러나 미군과 소련군이 남과 북에 들어오며 분단이 굳어졌고, 1948년 8월 15일 대한민국 정부가 수립됐습니다. 1950년 6월 25일 한국전쟁이 일어나 수많은 사람이 희생되고 삶의 터전을 잃었습니다. 휴전 뒤 산업화가 진행됐고, 4·19혁명·5·18민주화운동·6월 민주항쟁을 거치며 시민이 민주주의를 넓혔습니다.",event:"1945 광복 · 1948 정부 수립 · 1950 한국전쟁 · 민주화운동",life:"귀환과 분단, 피란 생활, 전후 복구, 도시화와 산업화",heritage:"광복 기록 · 전쟁기록 · 산업유산 · 민주화운동 기록",question:"광복의 기쁨이 곧 분단과 전쟁의 아픔으로 이어진 까닭은 무엇일까요?"},
 today:{year:"1987~오늘",title:"민주주의와 세계 속의 대한민국",text:"1987년 이후 대통령 직선제가 자리 잡고 시민 참여가 확대됐습니다. 정보통신·반도체·자동차·바이오 산업이 성장했으며 영화, 드라마, K-pop, 웹툰과 음식도 세계와 만났습니다. 동시에 저출산, 기후위기, 불평등, 지역 격차와 한반도 평화라는 과제를 함께 풀어 가고 있습니다.",event:"민주주의 발전 · 정보화 · 한류 · 시민 참여",life:"디지털 일상, 다문화 사회, 세계와 실시간 교류",heritage:"오늘 우리가 만드는 기록과 생활문화",question:"50년 뒤 사람들에게 남기고 싶은 오늘의 문화는 무엇인가요?"}
};
function showEra(key){const d=eraData[key],year=d.year.replace('~','~<br>');$("#eraPanel").innerHTML=`<div class="year">${year}</div><div><h3>${d.title}</h3><p>${d.text}</p><div class="era-meta"><div><b>핵심 흐름</b><span>${d.event}</span></div><div><b>사람들의 생활</b><span>${d.life}</span></div><div><b>대표 문화유산</b><span>${d.heritage}</span></div></div><span class="fact">생각 질문 · ${d.question}</span></div>`;state.visited.add(key);$(`.era[data-era="${key}"]`).classList.add("visited");if(state.visited.size===9)earnStar("history","아홉 시대 탐험 완료!")}
showEra("gojoseon");$$('.era').forEach(btn=>btn.addEventListener('click',()=>{$$('.era').forEach(b=>b.classList.remove('active'));btn.classList.add('active');showEra(btn.dataset.era)}));

const trigramData={geon:{hanja:'乾',name:'건 · 하늘',title:'끊어지지 않은 세 효',text:'건괘는 하늘을 상징하며 태극기의 왼쪽 위에 자리합니다.'},gon:{hanja:'坤',name:'곤 · 땅',title:'끊어진 세 효',text:'곤괘는 땅을 상징하며 태극기의 오른쪽 아래에 자리합니다.'},gam:{hanja:'坎',name:'감 · 물',title:'가운데만 이어진 효',text:'감괘는 물을 상징하며 태극기의 오른쪽 위에 자리합니다.'},ri:{hanja:'離',name:'리 · 불',title:'가운데만 끊어진 효',text:'리괘는 불을 상징하며 태극기의 왼쪽 아래에 자리합니다.'}};
const viewedTrigrams=new Set();$$('.trigram').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();const wasActive=btn.classList.contains('active'),d=trigramData[btn.dataset.trigram];$$('.trigram').forEach(b=>b.classList.remove('active'));if(wasActive)return;btn.classList.add('active');$('#trigramHanja').textContent=d.hanja;$('#trigramName').textContent=d.name;$('#trigramTitle').textContent=d.title;$('#trigramText').textContent=d.text;viewedTrigrams.add(btn.dataset.trigram);if(viewedTrigrams.size===4)earnStar('flag','건곤감리 탐구 완료!')}));$('.flag-stage').addEventListener('click',()=>$$('.trigram').forEach(b=>b.classList.remove('active')));

const cultureData={
 music:{emoji:'🥁',title:'국악에서 K-pop까지',text:'한국 음악은 궁중의 정악, 민간의 풍물과 민요, 긴 이야기를 노래하는 판소리 등 여러 갈래로 발전했습니다. 오늘날에는 전통 장단과 악기 소리를 힙합·팝·전자음악과 결합하는 시도가 이어집니다.',topics:[['장단','장구의 덩·덕·쿵처럼 소리의 강약과 길이를 조직하는 리듬 틀입니다. 굿거리·자진모리 등 장단마다 속도와 느낌이 다릅니다.'],['악기','가야금·거문고는 줄을 울리고, 대금·피리는 바람을 불며, 장구·북·징·꽹과리는 장단과 신호를 만듭니다.'],['판소리','한 명의 소리꾼과 고수가 긴 이야기를 노래·말·몸짓으로 풀어냅니다. 관객의 추임새도 공연의 일부입니다.'],['오늘의 변화','국악 크로스오버, 사극 음악, K-pop의 전통 의상·춤·악기 활용처럼 옛 소리가 새롭게 해석됩니다.']],connection:'공통점: 리듬, 몸짓, 무대 연출과 관객의 호응은 전통 공연과 현대 무대 모두에서 중요합니다.',tryIt:'체험 아이디어 · 버튼 네 개를 눌러 장구·북·징·꽹과리 소리를 조합하는 장단 메이커를 만들어 보세요.'},
 hanbok:{emoji:'🪭',title:'선과 색, 움직임의 옷 한복',text:'한복은 저고리와 치마·바지를 중심으로 하며, 평면적인 옷감이 몸의 움직임에 따라 풍성한 선을 만듭니다. 시대·계층·행사에 따라 모양과 재료가 달랐습니다.',topics:[['기본 구성','저고리, 치마 또는 바지, 겉옷으로 구성됩니다. 고름·깃·동정·소매 등 각 부분에 이름과 기능이 있습니다.'],['색과 무늬','오방색은 방향과 자연의 기운을 상징했습니다. 신분·나이·행사에 따라 색과 자수 무늬를 다르게 사용했습니다.'],['생활과 예복','평상복은 활동성을, 혼례복·관복 같은 예복은 의식과 지위를 표현했습니다. 한복이 언제나 화려했던 것은 아닙니다.'],['오늘의 한복','생활한복, 교복, 무대 의상과 패션 디자인으로 변화하며 전통의 선과 매듭을 새롭게 활용합니다.']],connection:'관찰법: 저고리의 곡선, 치마와 바지의 여유, 옷고름이 움직일 때 만드는 선을 살펴보세요.',tryIt:'체험 아이디어 · 저고리·치마·바지의 색을 선택하면 오방색의 의미를 알려 주는 한복 코디 앱을 만들어 보세요.'},
 food:{emoji:'🍲',title:'자연과 시간이 만든 한식',text:'밥·국·반찬을 함께 차리는 상차림과 계절 식재료, 발효와 저장 기술이 한식의 중요한 특징입니다. 지역과 시대에 따라 같은 음식도 맛과 모습이 다양합니다.',topics:[['밥과 반찬','주식인 밥을 중심으로 국·찌개·나물·구이·김치 등을 함께 먹습니다. 반찬을 공유하는 문화도 특징입니다.'],['발효','김치와 간장·된장·고추장은 미생물과 시간이 맛을 변화시킵니다. 저장 방법인 동시에 지역의 맛을 만드는 기술입니다.'],['지역 음식','전주의 비빔밥, 전주의 음식만이 아니라 제주·강원·전라·경상·평안·함경 등 기후와 생산물에 따라 음식 문화가 달라집니다.'],['명절과 공동체','설의 떡국, 추석의 송편, 김장처럼 음식은 가족과 이웃이 함께 일하고 기억을 나누는 시간이기도 합니다.']],connection:'주의할 점: 한식을 맵고 빨간 음식 하나로만 설명하면 지역·계절·사찰·궁중·가정 음식의 다양성을 놓치게 됩니다.',tryIt:'체험 아이디어 · 재료 카드를 끌어 그릇에 담으면 지역과 영양 정보를 알려 주는 나만의 비빔밥 게임을 만들어 보세요.'},
 heritage:{emoji:'🏯',title:'기억을 이어 주는 문화유산',text:'문화유산은 궁궐이나 탑 같은 건축물만 뜻하지 않습니다. 기록, 기술, 노래, 춤, 의례처럼 사람이 기억하고 실천해 이어 가는 유산도 있습니다.',topics:[['유형유산','불국사·수원화성·고인돌처럼 형태가 있는 유산입니다. 재료와 구조, 주변 환경까지 함께 보존합니다.'],['기록유산','훈민정음 해례본·조선왕조실록·직지처럼 지식과 역사를 기록한 자료입니다.'],['무형유산','판소리·강강술래·매사냥·김장처럼 사람의 지식과 기술을 통해 이어집니다. 변화하며 전승될 수 있습니다.'],['보존과 활용','복원·기록·교육과 함께 시민이 안전하게 경험하는 방법을 고민합니다. 관광보다 유산의 의미와 공동체를 먼저 살펴야 합니다.']],connection:'핵심 질문: 오래된 모습을 지키는 것과 오늘의 삶 속에서 이어 가는 것은 어떻게 균형을 이룰 수 있을까요?',tryIt:'체험 아이디어 · 문화유산 사진을 누르면 유형·기록·무형 중 어디에 속하는지 맞히는 분류 게임을 만들어 보세요.'}
};
const dialog=$("#cultureDialog");$$('.culture-card').forEach(btn=>btn.addEventListener('click',()=>{const d=cultureData[btn.dataset.card];$('#dialogBody').innerHTML=`<div class="dialog-content"><span class="big">${d.emoji}</span><h3>${d.title}</h3><p>${d.text}</p><div class="culture-topics">${d.topics.map(t=>`<div class="culture-topic"><b>${t[0]}</b><span>${t[1]}</span></div>`).join('')}</div><div class="connection">${d.connection}</div><p class="try-it">${d.tryIt}</p></div>`;dialog.showModal();btn.classList.add('seen');if($$('.culture-card.seen').length===4)earnStar('culture','문화 네 분야 탐구 완료!')}));$('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});

$$('.game-tab').forEach(btn=>btn.addEventListener('click',()=>{$$('.game-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('.game-panel').forEach(p=>p.classList.remove('active'));$(`#${btn.dataset.game}Game`).classList.add('active')}));
const finds=['궁궐','북한산','장구','한식','서울'];function renderChecklist(){$('#huntChecklist').innerHTML=finds.map(x=>`<span class="${state.found.has(x)?'found':''}">${state.found.has(x)?'✓ ':''}${x}</span>`).join('');$('#foundCount').textContent=state.found.size}renderChecklist();$$('.hotspot').forEach(btn=>btn.addEventListener('click',()=>{state.found.add(btn.dataset.find);btn.classList.add('found');renderChecklist();if(state.found.size===5)earnStar('game','60초 문화 찾기 완료!')}));$('#resetHunt').addEventListener('click',()=>{state.found.clear();$$('.hotspot').forEach(b=>b.classList.remove('found'));renderChecklist()});

const quiz=[{q:'고구려·백제·신라와 함께 철 생산과 교역으로 성장한 나라는?',a:['가야','발해','대한제국'],c:0,why:'가야는 낙동강 유역의 철을 바탕으로 성장했습니다.'},{q:'고려의 문화유산이 아닌 것은?',a:['고려청자','팔만대장경','수원화성'],c:2,why:'수원화성은 조선 정조 때 건설됐습니다.'},{q:'태극기의 감괘가 상징하는 자연 요소는?',a:['하늘','물','불'],c:1,why:'감괘는 물·겨울·북쪽·지혜를 상징합니다.'},{q:'사람의 기술과 기억으로 이어지는 무형문화유산은?',a:['판소리','석굴암','금동대향로'],c:0,why:'판소리는 소리꾼과 고수, 관객의 참여로 전승됩니다.'}];
function renderQuiz(){const item=quiz[state.quizIndex];$('#quizStep').textContent=`문제 ${state.quizIndex+1} / ${quiz.length}`;$('#quizScore').textContent=`${state.quizScore}점`;$('#quizQuestion').textContent=item.q;$('#quizFeedback').textContent='';$('#nextQuestion').hidden=true;state.answered=false;$('#quizAnswers').innerHTML='';item.a.forEach((text,i)=>{const b=document.createElement('button');b.className='answer';b.textContent=`${i+1}. ${text}`;b.onclick=()=>answerQuiz(i,b);$('#quizAnswers').append(b)})}
function answerQuiz(i,button){if(state.answered)return;state.answered=true;const item=quiz[state.quizIndex];$$('.answer').forEach((b,idx)=>{b.disabled=true;if(idx===item.c)b.classList.add('correct')});if(i===item.c){state.quizScore+=25;$('#quizFeedback').textContent=`정답! ${item.why}`}else{button.classList.add('wrong');$('#quizFeedback').textContent=`아쉬워요. ${item.why}`}$('#quizScore').textContent=`${state.quizScore}점`;$('#nextQuestion').hidden=false;$('#nextQuestion').textContent=state.quizIndex===quiz.length-1?'결과 보기':'다음 문제'}
$('#nextQuestion').addEventListener('click',()=>{if(state.quizIndex<quiz.length-1){state.quizIndex++;renderQuiz()}else{$('#quizQuestion').textContent=`최종 점수 ${state.quizScore}점`;$('#quizAnswers').innerHTML='<button class="small-btn" id="retryQuiz">다시 도전하기</button>';$('#quizFeedback').textContent='각 해설을 읽으며 시대와 문화의 연결을 확인해 보세요.';$('#nextQuestion').hidden=true;$('#retryQuiz').onclick=()=>{state.quizIndex=0;state.quizScore=0;renderQuiz()}}});renderQuiz();

let stream=null,segmenter=null,segmenting=false,segmentLoop=0;const backgrounds={palace:'경복궁의 아침',hanok:'한옥마을 골목',hangang:'한강의 밤',dancheong:'단청 무늬'};const backgroundFiles={palace:'assets/fourcut-palace.png',hanok:'assets/fourcut-hanok.png',hangang:'assets/fourcut-hangang.png',dancheong:'assets/fourcut-dancheong.png'};let selectedBackground='palace';
function drawSegmentedPerson(results){const canvas=$('#personCanvas'),ctx=canvas.getContext('2d'),w=results.image.videoWidth||results.image.width,h=results.image.videoHeight||results.image.height;if(!w||!h)return;canvas.width=w;canvas.height=h;ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(w,0);ctx.scale(-1,1);ctx.drawImage(results.segmentationMask,0,0,w,h);ctx.globalCompositeOperation='source-in';ctx.drawImage(results.image,0,0,w,h);ctx.restore();ctx.globalCompositeOperation='source-over'}
async function runSegmentation(){if(!stream||segmenting)return;const video=$('#cameraVideo');if(video.readyState>=2){segmenting=true;try{await segmenter.send({image:video})}finally{segmenting=false}}segmentLoop=requestAnimationFrame(runSegmentation)}
async function initSegmentation(){if(segmenter)return true;if(typeof SelfieSegmentation==='undefined'){ $('#segmentStatus').textContent='⚠ 인물 분할 기능을 불러오지 못했습니다. 인터넷 연결을 확인해 주세요.';return false}segmenter=new SelfieSegmentation({locateFile:file=>`https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/${file}`});segmenter.setOptions({modelSelection:1,selfieMode:false});segmenter.onResults(drawSegmentedPerson);await segmenter.initialize();return true}
$('#cameraBtn').addEventListener('click',async()=>{if(stream){cancelAnimationFrame(segmentLoop);stream.getTracks().forEach(t=>t.stop());stream=null;$('#cameraVideo').srcObject=null;$('#personCanvas').getContext('2d').clearRect(0,0,$('#personCanvas').width,$('#personCanvas').height);$('#cameraPlaceholder').hidden=false;$('#captureBtn').hidden=true;$('#cameraBtn').textContent='카메라 켜기';return}try{$('#segmentStatus').textContent='인물 분할 모델을 준비하고 있어요…';if(!await initSegmentation())return;stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});const video=$('#cameraVideo');video.srcObject=stream;await video.play();$('#cameraPlaceholder').hidden=true;$('#captureBtn').hidden=false;$('#cameraBtn').textContent='카메라 끄기';$('#segmentStatus').textContent='🔒 사람만 기기 안에서 분리하며 사진은 전송·저장하지 않습니다.';runSegmentation()}catch(e){$('#segmentStatus').textContent='⚠ 카메라 또는 인물 분할을 시작하지 못했습니다.';toast('HTTPS 환경과 카메라 권한, 인터넷 연결을 확인해 주세요.')}});
$('#stickerSelect').addEventListener('change',e=>{selectedBackground=e.target.value;const frame=$('.camera-frame');frame.className=`camera-frame bg-${selectedBackground}`;$('#cameraSticker').textContent=backgrounds[selectedBackground]});
$('#captureBtn').addEventListener('click',()=>{const person=$('#personCanvas');if(!person.width)return;const cut=$$('.cut')[state.shots%4],c=document.createElement('canvas'),ctx=c.getContext('2d'),bg=new Image();c.width=900;c.height=1200;bg.onload=()=>{const scale=Math.max(c.width/bg.width,c.height/bg.height),sw=c.width/scale,sh=c.height/scale,sx=(bg.width-sw)/2,sy=(bg.height-sh)/2;ctx.drawImage(bg,sx,sy,sw,sh,0,0,c.width,c.height);const personRatio=person.width/person.height,ph=c.height*.82,pw=Math.min(c.width*.82,ph*personRatio),px=(c.width-pw)/2,py=c.height-ph-70;ctx.drawImage(person,px,py,pw,ph);ctx.fillStyle='rgba(7,26,49,.78)';ctx.fillRect(0,c.height-92,c.width,92);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='700 34px sans-serif';ctx.fillText(backgrounds[selectedBackground],c.width/2,c.height-38);cut.replaceChildren(c);state.shots++;toast(`${Math.min(state.shots,4)}번째 컷 촬영!`);if(state.shots===4)earnStar('camera','한국 여행 네 컷 완성!')};bg.src=backgroundFiles[selectedBackground]});
$('#clearPhotos').addEventListener('click',()=>{state.shots=0;$$('.cut').forEach((cut,i)=>cut.innerHTML=`<span>${i+1}</span>`);toast('네 컷을 비웠어요')});

const defaults=[{name:'구름이',favorite:'음악',text:'장구의 장단과 K-pop이 이어질 수 있다는 점이 신기했어요!',rating:5,date:'오늘'},{name:'별빛여행자',favorite:'역사',text:'삼국뿐 아니라 가야와 발해도 더 알아보고 싶어요.',rating:4,date:'오늘'}];
function getReviews(){try{return JSON.parse(localStorage.getItem('koreaReviews'))||defaults}catch{return defaults}}function escapeHTML(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function renderReviews(){const list=getReviews();$('#reviewCount').textContent=list.length;$('#reviewList').innerHTML=list.map(r=>`<article class="review-item"><header><strong>${escapeHTML(r.name)}</strong><span>${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</span></header><p>${escapeHTML(r.text)}</p><small>#${escapeHTML(r.favorite)} · ${r.date}</small></article>`).join('')}
$$('.rating button').forEach(btn=>btn.addEventListener('click',()=>{state.rating=+btn.dataset.rating;$$('.rating button').forEach((b,i)=>b.classList.toggle('on',i<state.rating))}));$$('.rating button').forEach(b=>b.classList.add('on'));$('#reviewForm').addEventListener('submit',e=>{e.preventDefault();const reviews=getReviews();reviews.unshift({name:$('#nickname').value,favorite:$('#favorite').value,text:$('#reviewText').value,rating:state.rating,date:new Date().toLocaleDateString('ko-KR')});localStorage.setItem('koreaReviews',JSON.stringify(reviews.slice(0,20)));e.target.reset();renderReviews();earnStar('review','여행 후기 등록 완료!')});renderReviews();
let audioCtx;$('#soundBtn').addEventListener('click',()=>{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.setValueAtTime(392,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(784,audioCtx.currentTime+.18);g.gain.setValueAtTime(.12,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.28);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.3);toast('효과음을 재생했어요')});
